version: '3.4'
services:
  vault:
    image: vault:latest
    container_name: vault
    restart: on-failure:10
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: 'https://0.0.0.0:8200'
      VAULT_API_ADDR: 'https://0.0.0.0:8202'
      VAULT_LOCAL_CONFIG: '{ "listener": [{ "tcp": { "address": "0.0.0.0:8200", "tls_disable": 1 } }], "storage": { "mssql": { "server": "10.23.94.7", "username": "vault", "password": "ASdasdqar3", "database": "Vault", "table": "vault", "appname": "vault" } }, "ui": true }'
      VAULT_TOKEN: 'f759cf1f-2e68-400f-8797-3fb398fa7b98'
    cap_add:
      - IPC_LOCK
    healthcheck:
      retries: 5
    command: server
 